openapi: 3.0.0
info:
  title: Example API - 1
  version: 1.0.0
paths:
  "/":
    get:
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
  "/found":
    get:
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object